## 一、Python基础
### 1. 列表推导式与条件赋值

在生成一个数字序列的时候，在`Python`中可以如下写出：

In [1]:
# 打印cell中的多个输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
L=[]
def my_func(x):
    return x**2;
for i in range(5):
    L.append(my_func(i))
L   


[0, 1, 4, 9, 16]

事实上可以利用列表推导式进行写法上的简化：`[* for i in *]`。其中，第一个`*`为映射函数，其输入为后面`i`指代的内容，第二个`*`表示迭代的对象。

In [3]:
[my_func(i) for i in range(5)]

[0, 1, 4, 9, 16]

列表表达式还支持多层嵌套，如下面的例子中第一个`for`为外层循环，第二个为内层循环：

In [4]:
[m+"-"+n for m in ("a","b") for n in ("c","d")]

['a-c', 'a-d', 'b-c', 'b-d']

除了列表推导式，另一个实用的语法糖是带有`if`选择的条件赋值，其形式为`value = a if condition else b`：

In [5]:
value="love" if 2>1 else "like"
value
value="love" if 2>2 else "like"
value
value="love" if 2>3 else "like"
value

'love'

'like'

'like'

等价于如下的写法：
```python
a, b = 'cat', 'dog'
condition = 2 > 1 # 此时为True
if condition:
    value = a
else:
    value = b
```

下面举一个例子，截断列表中超过5的元素，即超过5的用5代替，小于5的保留原来的值：

In [6]:
a=[1,1,5,2,3,6,8]
[5 if i>=5 else i for i in a]

[1, 1, 5, 2, 3, 5, 5]

### 2. 匿名函数与map方法

有一些函数的定义具有清晰简单的映射关系，例如上面的`my_func`函数，这时候可以用匿名函数的方法简洁地表示：

（入参由lambda指定）

In [7]:
my_func=lambda x:x**2
my_func(10)

100

In [8]:
my_func = lambda x,y:x+y
my_func(3,5)

8

但上面的用法其实违背了“匿名”的含义，事实上<font color=red>它往往在无需多处调用的场合进行使用</font>，例如上面列表推导式中的例子，用户不关心函数的名字，只关心这种映射的关系：

In [9]:
[(lambda x:x**2)(i) for i in range(5)]
[i**2 for i in range(5)]

[0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]

对于上述的这种列表推导式的匿名函数映射，`Python`中提供了`map`函数来完成，它返回的是一个`map`对象，需要通过`list`转为列表：

In [10]:
list(map(lambda x:x**2,range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

对于多个输入值的函数映射，可以通过追加迭代对象实现：

In [11]:
list(map(lambda x,y:str(x)+y,range(5),list('abcde')))

['0a', '1b', '2c', '3d', '4e']

### 3. zip对象与enumerate方法

`zip`函数能够把多个可迭代对象打包成一个元组构成的可迭代对象，它返回了一个`zip`对象，通过`tuple`, `list`可以得到相应的打包结果：

<font color="red">胡胡：zip是用来组成一一对应关系的利器！！可是是一对一，也可以是一对一对一</font>

In [12]:
# L1=list("abcd")
# L2=list("efgh")
# L3=list("jklm")
L1,L2,L3 = list("abcd"),list("efgh"),list("jklm")
list(zip(L1,L2,L3))
tuple(zip(L1,L2,L3))

[('a', 'e', 'j'), ('b', 'f', 'k'), ('c', 'g', 'l'), ('d', 'h', 'm')]

(('a', 'e', 'j'), ('b', 'f', 'k'), ('c', 'g', 'l'), ('d', 'h', 'm'))

往往会在循环迭代的时候使用到`zip`函数：

In [13]:
for x,y,z in zip(L1,L2,L3):
    print(x+"-"+y+"-"+z)

a-e-j
b-f-k
c-g-l
d-h-m


`enumerate`是一种特殊的打包，它可以在迭代时绑定迭代元素的遍历序号：

<font color="red">`enumerate`迭代器生成的结果是索引index和value值</font>

In [14]:
a=list("love")
for i,value in enumerate(a):
    print(i,value)

0 l
1 o
2 v
3 e


用`zip`对象也能够简单地实现这个功能：

In [15]:
for index,value in zip(range(len(a)),a):
    print(index,value)

0 l
1 o
2 v
3 e


当需要对两个列表建立字典映射时，可以利用`zip`对象：

In [16]:
dict(zip(L1,L2))

{'a': 'e', 'b': 'f', 'c': 'g', 'd': 'h'}

既然有了压缩函数，那么`Python`也提供了`*`操作符和`zip`联合使用来进行解压操作：

In [17]:
zipped = list(zip(L1,L2,L3))
zipped
[*zip(zipped)]
list(zip(*zipped))# 三个元组分别对应原来的列表
[*zip(*zipped)]# 三个元组分别对应原来的列表

[('a', 'e', 'j'), ('b', 'f', 'k'), ('c', 'g', 'l'), ('d', 'h', 'm')]

[(('a', 'e', 'j'),),
 (('b', 'f', 'k'),),
 (('c', 'g', 'l'),),
 (('d', 'h', 'm'),)]

[('a', 'b', 'c', 'd'), ('e', 'f', 'g', 'h'), ('j', 'k', 'l', 'm')]

[('a', 'b', 'c', 'd'), ('e', 'f', 'g', 'h'), ('j', 'k', 'l', 'm')]

`[*aaa]=list(aaa)`  补一下`*`的用法

## 二、Numpy基础
### 1. np数组的构造
最一般的方法是通过`array`来构造：

In [18]:
import numpy as np
np.array([1,2,5])

array([1, 2, 5])

下面讨论一些特殊数组的生成方式：

【a】等差序列：`np.linspace`, `np.arange`

In [19]:
np.linspace(1,10,9) # 起始、终止（包含）、样本个数
np.linspace(1,10,10) # 起始、终止（包含）、样本个数
np.linspace(1,10,11) # 起始、终止（包含）、样本个数

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [20]:
np.arange(1,10,2) # 起始、终止（不包含）、步长
np.arange(1,10,3) # 起始、终止（不包含）、步长
np.arange(10) 
np.arange(2,10)# 默认步长为1

array([1, 3, 5, 7, 9])

array([1, 4, 7])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([2, 3, 4, 5, 6, 7, 8, 9])

【b】特殊矩阵：`zeros`,`ones`, `eye`, `full`

In [21]:
np.zeros(10)
np.zeros(10).shape
np.zeros((2,3))# 传入元素表示各维度大小
np.zeros((2,3)).shape

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

(10,)

array([[0., 0., 0.],
       [0., 0., 0.]])

(2, 3)

In [22]:
np.ones(10)
np.ones(10).shape
np.ones((2,3))# 传入元素表示各维度大小
np.ones((2,3)).shape

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

(10,)

array([[1., 1., 1.],
       [1., 1., 1.]])

(2, 3)

In [23]:
np.eye(5) # 5*5的单位矩阵

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(5,k=1)# 偏移主对角线1个单位的伪单位矩阵

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.full((2,4),5)# 元组传入大小，10表示填充数值

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [26]:
np.full((2,4),[1,2,5,8])# 每行填入相同的列表

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

【c】随机矩阵：`np.random`

最常用的随机生成函数为`rand`, `randn`, `randint`, `choice`，它们分别表示0-1均匀分布的随机数组、标准正态的随机数组、随机整数组和随机列表抽样：

In [27]:
np.random.rand(5)# 生成服从0-1均匀分布的五个随机数

array([0.85240442, 0.92776679, 0.77996211, 0.10092751, 0.33449651])

In [28]:
np.random.rand(3,4) # 注意这里传入的不是元组，每个维度大小分开输入

array([[0.74951543, 0.47540769, 0.62001683, 0.29361745],
       [0.72389667, 0.41004981, 0.2348996 , 0.99844331],
       [0.16494271, 0.78220051, 0.77820977, 0.61582492]])

对于服从区间`a`到`b`上的均匀分布可以如下生成：

In [29]:
a,b=3,10
(b-a)*np.random.rand(5)+a

array([7.95543699, 6.72005352, 4.97796221, 3.02655826, 3.03603701])

一般的，可以选择已有的库函数：

In [30]:
np.random.uniform(3,10,5)

array([7.87136271, 9.97938608, 6.91496482, 7.03522188, 9.21381009])

In [31]:
np.random.randn(5)
np.random.randn(4,3)

array([0.87652063, 0.3292233 , 0.58507127, 0.66448675, 1.26869855])

array([[-0.05365243, -1.46604236, -0.61070404],
       [ 1.0020691 ,  0.3249995 , -0.57892987],
       [-1.00110822,  0.26903187, -0.09586379],
       [-0.46549077,  0.96488091,  0.54671071]])

对于服从方差为$\sigma^2$均值为$\mu$的一元正态分布可以如下生成：

In [32]:
mu,sigma=3,2.5
mu+np.random.randn(10)*sigma

array([ 7.17014579,  3.06904705,  1.10983351,  5.60269754, 11.1174536 ,
        0.11498339,  1.28977092,  3.38439137,  5.38442651,  4.62963935])

同样的，也可选择从已有函数生成：

In [33]:
np.random.normal(3,2.5,10) #输入参数分别为 mu，sigma，size
np.random.normal(3,2.5,10).shape

array([ 0.38719667,  4.46591199,  5.04113702, -1.16547506,  6.09917927,
        4.38983355,  4.3463166 ,  5.70138757,  5.16950761,  3.68586569])

(10,)

`randint`可以指定生成随机整数的最小值最大值（不包含）和维度大小：

In [34]:
low,high,size=3,10,(2,3)
np.random.randint(low,high,size)

array([[8, 8, 6],
       [8, 6, 4]])

`choice`可以从给定的列表中，以一定概率和方式抽取结果，当不指定概率`p`时为均匀采样，默认抽取方式为有放回抽样(`replace=True`)：

In [35]:
my_list = ["b","a","t","d"]
np.random.choice(my_list,2,replace=True,p=[0.1,0.7,0.1,0.1])
np.random.choice(my_list,2,replace=False,p=[0.1,0.7,0.1,0.1])
np.random.choice(my_list,2,replace=True,p=[0.1,0.0,0.8,0.1])
np.random.choice(my_list, (3,3),replace=True,p=[0.1,0.0,0.8,0.1])

array(['t', 'a'], dtype='<U1')

array(['t', 'b'], dtype='<U1')

array(['t', 'd'], dtype='<U1')

array([['t', 't', 't'],
       ['t', 't', 't'],
       ['d', 't', 't']], dtype='<U1')

当返回的元素个数与原列表相同时，不放回抽样等价于使用`permutation`函数，即打散原列表：

In [36]:
np.random.permutation(my_list)

array(['d', 'a', 'b', 't'], dtype='<U1')

最后，需要提到的是随机种子，它能够固定随机数的输出结果：

<font color="red">如果需要取消种子，则`np.random.seed(None)`</font>

In [73]:
np.random.seed(12)
np.random.rand(3)
np.random.seed(12)
np.random.rand(3)

np.random.seed(13)
np.random.rand(3)
np.random.seed(13)
np.random.rand(3)

np.random.seed(None)
np.random.rand(3)
np.random.rand(3)


array([0.15416284, 0.7400497 , 0.26331502])

array([0.15416284, 0.7400497 , 0.26331502])

array([0.77770241, 0.23754122, 0.82427853])

array([0.77770241, 0.23754122, 0.82427853])

array([0.28526093, 0.56123562, 0.75103182])

array([0.32598672, 0.3325461 , 0.11861942])

### 2. np数组的变形与合并
【a】转置：`T`

In [38]:
np.random.randint(2,10,(2,3))
np.random.randint(2,10,(2,3)).T

array([[6, 3, 6],
       [4, 5, 4]])

array([[6, 8],
       [8, 8],
       [4, 7]])

【b】合并操作：`r_`, `c_`

对于二维数组而言，`r_`和`c_`分别表示上下合并和左右合并：

In [39]:
a = np.random.randint(2,10,(2,3))
b = np.random.randint(2,10,(2,3))
a
b
np.r_[a,b]
np.c_[a,b]

array([[7, 4, 3],
       [5, 6, 4]])

array([[2, 5, 7],
       [5, 5, 8]])

array([[7, 4, 3],
       [5, 6, 4],
       [2, 5, 7],
       [5, 5, 8]])

array([[7, 4, 3, 2, 5, 7],
       [5, 6, 4, 5, 5, 8]])

<font color="red">一维数组和二维数组进行合并时，应当把一维数组其视作列向量，在长度匹配的情况下只能够使用左右合并的`c_`操作，不可以进行`r_`操作</font>：

In [40]:
try:
     np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
     Err_Msg = e
Err_Msg
np.array([0,0]).shape
np.zeros((2,1)).shape

ValueError('all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)')

(2,)

(2, 1)

In [41]:
np.array([1,2]).shape
np.ones((2,2)).shape
np.c_[np.array([1,2]),np.ones((2,2))]
np.c_[np.array([1,2]),np.ones((2,3))]

(2,)

(2, 2)

array([[1., 1., 1.],
       [2., 1., 1.]])

array([[1., 1., 1., 1.],
       [2., 1., 1., 1.]])

In [42]:
np.r_[np.array([3,2]),np.ones(2)]


array([3., 2., 1., 1.])

【c】维度变换：`reshape`

`reshape`能够帮助用户把原数组按照新的维度重新排列。在使用时有两种模式，分别为`C`模式和`F`模式，分别以逐行和逐列的顺序进行填充读取。

In [43]:
target = np.arange(8).reshape(2,4)
target

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
target.reshape((4,2),order="C") # 按行读取和填充

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

<font color="red">`order="F"`按列读取和填充 这块儿没懂</font>

In [45]:
target.reshape((4,2),order="F") # 按列读取和填充  

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

特别地，由于被调用数组的大小是确定的，`reshape`允许有一个维度存在空缺，此时只需填充-1即可：<font color="red">但是！必须保证是可以除尽的！比如9个元素reshape为(4,-1)是会报错的</font>

In [46]:
target.reshape(4,-1)
try:
    target.reshape(3,-1)
except Exception as e:
     Err_Msg = e
Err_Msg

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

ValueError('cannot reshape array of size 8 into shape (3,newaxis)')

下面将`n*1`大小的数组转为1维数组的操作是经常使用的：

In [47]:
target.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7])

### 3. np数组的切片与索引
数组的切片模式支持使用`slice`类型的`start:end:step`切片，还可以直接传入列表指定某个维度的索引进行切片：

In [48]:
target = np.arange(12).reshape(3,4)
target

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
target[:-1,[1,3]]

array([[1, 3],
       [5, 7]])

此外，还可以利用`np.ix_`在对应的维度上使用布尔索引，但此时不能使用`slice`切片：

In [50]:
np.ix_([True,False,True],[False,True,True])
np.ix_([True,False,True],[False,True,True,False])

target[np.ix_([True,False,True],[False,True,True])]
target[np.ix_([True,False,True],[False,True,True,True])]

(array([[0],
        [2]], dtype=int64),
 array([[1, 2]], dtype=int64))

(array([[0],
        [2]], dtype=int64),
 array([[1, 2]], dtype=int64))

array([[ 1,  2],
       [ 9, 10]])

array([[ 1,  2,  3],
       [ 9, 10, 11]])

当数组维度为1维时，可以直接进行布尔索引，而无需`np.ix_`：

In [51]:
new=np.arange(10)
new
new[new%3==2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([2, 5, 8])

### 4. 常用函数
为了简单起见，这里假设下述函数输入的数组都是一维的。

【a】`where`

`where`是一种条件函数，可以指定满足条件与不满足条件位置对应的填充值：

In [53]:
a=np.arange(10)
a
np.where(a>5,5,a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 5, 5, 5, 5])

【b】`nonzero`, `argmax`, `argmin`

这三个函数返回的都是<font color=red size=3>索引</font>，`nonzero`返回非零数的索引，`argmax`, `argmin`分别返回最大和最小数的索引：

In [87]:
np.random.seed(1)
a=np.arange(5)-2
a
a=np.random.permutation(a)
a
np.nonzero(a)
np.argmax(a)
np.argmin(a)
a[np.argmax(a)]
a.nonzero()
a.argmax()
a.argmin()

array([-2, -1,  0,  1,  2])

array([ 0, -1,  2, -2,  1])

(array([1, 2, 3, 4], dtype=int64),)

2

3

2

(array([1, 2, 3, 4], dtype=int64),)

2

3

【c】`any`, `all`

`any`指当序列至少 **存在一个** `True`或非零元素时返回`True`，否则返回`False`

`all`指当序列元素 **全为** `True`或非零元素时返回`True`，否则返回`False`

可以通过`np.all(a)` 也可以通过`a.all()`调用

In [86]:
a=np.arange(5)-3
a
a=np.random.permutation(a)
a
np.any(a)
np.all(a)
np.any(a==1)
np.any(a==5)
np.all(a==1)
a.any()
a.all()

array([-3, -2, -1,  0,  1])

array([-3, -1,  1,  0, -2])

True

False

True

False

False

True

False

【d】`cumprod`, `cumsum`, `diff`

`cumprod`, `cumsum`分别表示累乘和累加函数，返回同长度的数组，`diff`表示和前一个元素做差，由于第一个元素为缺失值，因此在默认参数情况下，返回长度是原数组减1

In [76]:
a=np.arange(10)+1
np.cumprod(a)
np.cumsum(a)
np.diff(a)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [85]:
0.98**15*500
1.03**15*500
1.03**15*500-0.98**15*500

369.2845513227019

778.9837083003825

409.6991569776807

【e】 统计函数

常用的统计函数包括`max, min, mean, median, std, var, sum, quantile`，其中分位数计算是全局方法，因此不能通过`array.quantile`的方法调用：

In [99]:
a=np.arange(10)
a
a.max()
a.min()
a.mean()
np.median(a)
a.std()
a.var()
a.sum()
np.quantile(a,0.25)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

9

0

4.5

4.5

2.8722813232690143

8.25

45

2.25

但是对于含有缺失值的数组，它们返回的结果也是缺失值，如果需要略过缺失值，必须使用`nan*`类型的函数，上述的几个统计函数都有对应的`nan*`函数。且不可以用`array.nan*`的方式调用

In [110]:
a=np.array([0,1,2,np.nan])
a
a.max()
np.nanmax(a)
np.nanquantile(a,0.5)

array([ 0.,  1.,  2., nan])

nan

2.0

1.0

对于协方差和相关系数分别可以利用`cov, corrcoef`如下计算：<font color=red-purple size=5>需要再补一下协方差和相关系数的知识！</font>

In [111]:
a=np.array([2,4,7,-1])
b=np.array([2,4,7,6])
np.cov(a,b)
np.corrcoef(a,b)

array([[11.33333333,  2.        ],
       [ 2.        ,  4.91666667]])

array([[1.        , 0.26792657],
       [0.26792657, 1.        ]])

最后，需要说明二维`Numpy`数组中统计函数的`axis`参数，它能够进行某一个维度下的统计特征计算，<font color=red-purple>当`axis=0`时结果为列的统计指标，当`axis=1`时结果为行的统计指标：</font>

In [117]:
a=np.arange(1,13,2).reshape(2,-1)
a
a.sum(0)
a.sum(axis=0)
a.sum(axis=1)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

array([ 8, 12, 16])

array([ 8, 12, 16])

array([ 9, 27])

### 5. 广播机制

广播机制用于处理两个不同维度数组之间的操作，这里只讨论不超过两维的数组广播机制。

【a】标量和数组的操作

当一个标量和数组进行运算时，标量会自动把大小扩充为数组大小，之后进行逐元素操作：

In [121]:
res=3*np.ones((2,3))+5
res
res*2
1/res

array([[8., 8., 8.],
       [8., 8., 8.]])

array([[16., 16., 16.],
       [16., 16., 16.]])

array([[0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125]])

【b】二维数组之间的操作

<font color=red>当两个数组维度完全一致时，使用对应元素的操作，否则会报错，除非其中的某个数组的维度是$m×1$或者$1×n$，那么会扩充其具有$1$的维度为另一个数组对应维度的大小。</font>例如，$1×2$数组和$3×2$数组做逐元素运算时会把第一个数组扩充为$3×2$，扩充时的对应数值进行赋值。但是，需要注意的是，如果第一个数组的维度是$1×3$，那么由于在第二维上的大小不匹配且不为$1$，此时报错。

In [130]:
a=np.ones((2,3))*2
a
a*np.array([3,4,5])
a*np.array([[3],[4]])
a*a
a/a
a-a

array([[2., 2., 2.],
       [2., 2., 2.]])

array([[ 6.,  8., 10.],
       [ 6.,  8., 10.]])

array([[6., 6., 6.],
       [8., 8., 8.]])

array([[4., 4., 4.],
       [4., 4., 4.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

array([[0., 0., 0.],
       [0., 0., 0.]])

【c】一维数组与二维数组的操作

当一维数组$A_k$与二维数组$B_{m,n}$操作时，等价于把一维数组视作$A_{1,k}$的二维数组，使用的广播法则与【b】中一致，当$k!=n$且$k,n$都不是$1$时报错。

<font color=red>一维数组长度需要与二维数组的列相同</font>

In [131]:
np.ones(3)+np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [134]:
try:
    np.ones(3)+np.ones((3,2))
except Exception as e:
    ErrMsg=e
ErrMsg

ValueError('operands could not be broadcast together with shapes (3,) (3,2) ')

### 6. 向量与矩阵的计算
【a】向量内积：`dot`

$$\rm \mathbf{a}\cdot\mathbf{b} = \sum_ia_ib_i$$
$\rm \mathbf{a}\cdot\mathbf{b} = \sum_ia_ib_i$

In [136]:
a=np.array([1,2,3])
b=np.array([4,5,8])
a.dot(b)
np.dot(a,b)

38

38

In [141]:
c=np.arange(12).reshape(3,4)
d=np.arange(12).reshape(3,4)
c
d
try:
    c.dot(d)
except Exception as e:
    ErrMsg = e
ErrMsg

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

ValueError('shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)')

In [142]:
c=np.arange(12).reshape(3,4)
e=np.arange(12).reshape(4,3)
c
e
c.dot(e)
e.dot(c)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

【b】向量范数和矩阵范数：`np.linalg.norm`  <font color=red-purple>百度了一下，看不懂。感觉需要补数学知识</font>

在矩阵范数的计算中，最重要的是`ord`参数，可选值如下：

| ord | norm for matrices | norm for vectors |
| :---- | ----: | ----: |
| None   | Frobenius norm | 2-norm |
| 'fro'  | Frobenius norm  | / |
| 'nuc'  | nuclear norm    | / |
| inf    | max(sum(abs(x), axis=1))   | max(abs(x)) |
| -inf   | min(sum(abs(x), axis=1))  |  min(abs(x)) |
| 0      | /   |  sum(x != 0) |
| 1      | max(sum(abs(x), axis=0))  |  as below |
| -1     | min(sum(abs(x), axis=0))   |  as below |
| 2      | 2-norm (largest sing. value) | as below |
| -2     | smallest singular value    | as below |
| other  | /   | sum(abs(x)\*\*ord)\*\*(1./ord) |

【c】矩阵乘法：`@`

$$\rm [\mathbf{A}_{m\times p}\mathbf{B}_{p\times n}]_{ij} = \sum_{k=1}^p\mathbf{A}_{ik}\mathbf{B}_{kj}$$

## 三、练习
### Ex1：利用列表推导式写矩阵乘法
一般的矩阵乘法根据公式，可以由三重循环写出，请将其改写为列表推导式的形式。

In [145]:
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item
(np.abs((M1@M2 - res) < 1e-15)).all() # 排除数值误差

True

### Ex2：更新矩阵
设矩阵 $A_{m×n}$ ，现在对 $A$ 中的每一个元素进行更新生成矩阵 $B$ ，更新方法是 $B_{ij}=A_{ij}\sum_{k=1}^n\frac{1}{A_{ik}}$ ，例如下面的矩阵为 $A$ ，则 $B_{2,2}=5\times(\frac{1}{4}+\frac{1}{5}+\frac{1}{6})=\frac{37}{12}$ ，请利用 `Numpy` 高效实现。
$$\begin{split}A=\left[ \begin{matrix} 1 & 2 &3\\4&5&6\\7&8&9 \end{matrix} \right]\end{split}$$

### Ex3：卡方统计量

设矩阵$A_{m\times n}$，记$B_{ij} = \frac{(\sum_{i=1}^mA_{ij})\times (\sum_{j=1}^nA_{ij})}{\sum_{i=1}^m\sum_{j=1}^nA_{ij}}$，定义卡方值如下：
$$\chi^2 = \sum_{i=1}^m\sum_{j=1}^n\frac{(A_{ij}-B_{ij})^2}{B_{ij}}$$
请利用`Numpy`对给定的矩阵$A$计算$\chi^2$ 

In [146]:
np.random.seed(0)
A = np.random.randint(10, 20, (8, 5))

### Ex4：改进矩阵计算的性能
设$Z$为$m×n$的矩阵，$B$和$U$分别是$m×p$和$p×n$的矩阵，$B_i$为$B$的第$i$行，$U_j$为$U$的第$j$列，下面定义$\displaystyle R=\sum_{i=1}^m\sum_{j=1}^n\|B_i-U_j\|_2^2Z_{ij}$，其中$\|\mathbf{a}\|_2^2$表示向量$a$的分量平方和$\sum_i a_i^2$。

现有某人根据如下给定的样例数据计算$R$的值，请充分利用`Numpy`中的函数，基于此问题改进这段代码的性能。

In [147]:
np.random.seed(0)
m, n, p = 100, 80, 50
B = np.random.randint(0, 2, (m, p))
U = np.random.randint(0, 2, (p, n))
Z = np.random.randint(0, 2, (m, n))
def solution(B=B, U=U, Z=Z):
    L_res = []
    for i in range(m):
        for j in range(n):
            norm_value = ((B[i]-U[:,j])**2).sum()
            L_res.append(norm_value*Z[i][j])
    return sum(L_res)
solution(B, U, Z)

100566

### Ex5：连续整数的最大长度

输入一个整数的`Numpy`数组，返回其中严格递增连续整数子数组的最大长度，正向是指递增方向。例如，输入\[1,2,5,6,7\]，\[5,6,7\]为具有最大长度的连续整数子数组，因此输出3；输入\[3,2,1,2,3,4,6\]，\[1,2,3,4\]为具有最大长度的连续整数子数组，因此输出4。请充分利用`Numpy`的内置函数完成。（提示：考虑使用`nonzero, diff`函数）