## 一、Python基础
### 1. 列表推导式与条件赋值

在生成一个数字序列的时候，在`Python`中可以如下写出：

In [12]:
# 打印cell中的多个输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [6]:
L=[]
def my_func(x):
    return x**2;
for i in range(5):
    L.append(my_func(i))
L   


[0, 1, 4, 9, 16]

事实上可以利用列表推导式进行写法上的简化：`[* for i in *]`。其中，第一个`*`为映射函数，其输入为后面`i`指代的内容，第二个`*`表示迭代的对象。

In [7]:
[my_func(i) for i in range(5)]

[0, 1, 4, 9, 16]

列表表达式还支持多层嵌套，如下面的例子中第一个`for`为外层循环，第二个为内层循环：

In [8]:
[m+"-"+n for m in ("a","b") for n in ("c","d")]

['a-c', 'a-d', 'b-c', 'b-d']

除了列表推导式，另一个实用的语法糖是带有`if`选择的条件赋值，其形式为`value = a if condition else b`：

In [13]:
value="love" if 2>1 else "like"
value
value="love" if 2>2 else "like"
value
value="love" if 2>3 else "like"
value

'love'

'like'

'like'

等价于如下的写法：
```python
a, b = 'cat', 'dog'
condition = 2 > 1 # 此时为True
if condition:
    value = a
else:
    value = b
```

下面举一个例子，截断列表中超过5的元素，即超过5的用5代替，小于5的保留原来的值：

In [14]:
a=[1,1,5,2,3,6,8]
[5 if i>=5 else i for i in a]

[1, 1, 5, 2, 3, 5, 5]

### 2. 匿名函数与map方法

有一些函数的定义具有清晰简单的映射关系，例如上面的`my_func`函数，这时候可以用匿名函数的方法简洁地表示：

（入参由lambda指定）

In [15]:
my_func=lambda x:x**2
my_func(10)

100

In [16]:
my_func = lambda x,y:x+y
my_func(3,5)

8

但上面的用法其实违背了“匿名”的含义，事实上<font color=red>它往往在无需多处调用的场合进行使用</font>，例如上面列表推导式中的例子，用户不关心函数的名字，只关心这种映射的关系：

In [24]:
[(lambda x:x**2)(i) for i in range(5)]
[i**2 for i in range(5)]

[0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]

对于上述的这种列表推导式的匿名函数映射，`Python`中提供了`map`函数来完成，它返回的是一个`map`对象，需要通过`list`转为列表：

In [31]:
list(map(lambda x:x**2,range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

对于多个输入值的函数映射，可以通过追加迭代对象实现：

In [33]:
list(map(lambda x,y:str(x)+y,range(5),list('abcde')))

['0a', '1b', '2c', '3d', '4e']

### 3. zip对象与enumerate方法

`zip`函数能够把多个可迭代对象打包成一个元组构成的可迭代对象，它返回了一个`zip`对象，通过`tuple`, `list`可以得到相应的打包结果：

<font color="red">胡胡：zip是用来组成一一对应关系的利器！！可是是一对一，也可以是一对一对一</font>

In [52]:
# L1=list("abcd")
# L2=list("efgh")
# L3=list("jklm")
L1,L2,L3 = list("abcd"),list("efgh"),list("jklm")
list(zip(L1,L2,L3))
tuple(zip(L1,L2,L3))

[('a', 'e', 'j'), ('b', 'f', 'k'), ('c', 'g', 'l'), ('d', 'h', 'm')]

(('a', 'e', 'j'), ('b', 'f', 'k'), ('c', 'g', 'l'), ('d', 'h', 'm'))

往往会在循环迭代的时候使用到`zip`函数：

In [40]:
for x,y,z in zip(L1,L2,L3):
    print(x+"-"+y+"-"+z)

a-e-j
b-f-k
c-g-l
d-h-m


`enumerate`是一种特殊的打包，它可以在迭代时绑定迭代元素的遍历序号：

<font color="red">`enumerate`迭代器生成的结果是索引index和value值</font>

In [41]:
a=list("love")
for i,value in enumerate(a):
    print(i,value)

0 l
1 o
2 v
3 e


用`zip`对象也能够简单地实现这个功能：

In [44]:
for index,value in zip(range(len(a)),a):
    print(index,value)

0 l
1 o
2 v
3 e


当需要对两个列表建立字典映射时，可以利用`zip`对象：

In [48]:
dict(zip(L1,L2))

{'a': 'e', 'b': 'f', 'c': 'g', 'd': 'h'}

既然有了压缩函数，那么`Python`也提供了`*`操作符和`zip`联合使用来进行解压操作：

In [57]:
zipped = list(zip(L1,L2,L3))
zipped
[*zip(zipped)]
list(zip(*zipped))# 三个元组分别对应原来的列表
[*zip(*zipped)]# 三个元组分别对应原来的列表

[('a', 'e', 'j'), ('b', 'f', 'k'), ('c', 'g', 'l'), ('d', 'h', 'm')]

[(('a', 'e', 'j'),),
 (('b', 'f', 'k'),),
 (('c', 'g', 'l'),),
 (('d', 'h', 'm'),)]

[('a', 'b', 'c', 'd'), ('e', 'f', 'g', 'h'), ('j', 'k', 'l', 'm')]

[('a', 'b', 'c', 'd'), ('e', 'f', 'g', 'h'), ('j', 'k', 'l', 'm')]

`[*aaa]=list(aaa)`  补一下`*`的用法

## 二、Numpy基础
### 1. np数组的构造
最一般的方法是通过`array`来构造：

In [63]:
import numpy as np
np.array([1,2,5])

array([1, 2, 5])

下面讨论一些特殊数组的生成方式：

【a】等差序列：`np.linspace`, `np.arange`

In [69]:
np.linspace(1,10,9) # 起始、终止（包含）、样本个数
np.linspace(1,10,10) # 起始、终止（包含）、样本个数
np.linspace(1,10,11) # 起始、终止（包含）、样本个数

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [71]:
np.arange(1,10,2) # 起始、终止（不包含）、步长
np.arange(1,10,3) # 起始、终止（不包含）、步长

array([1, 3, 5, 7, 9])

array([1, 4, 7])

【b】特殊矩阵：`zeros`,`ones`, `eye`, `full`

In [76]:
np.zeros(10)
np.zeros(10).shape
np.zeros((2,3))# 传入元素表示各维度大小
np.zeros((2,3)).shape

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

(10,)

array([[0., 0., 0.],
       [0., 0., 0.]])

(2, 3)

In [77]:
np.ones(10)
np.ones(10).shape
np.ones((2,3))# 传入元素表示各维度大小
np.ones((2,3)).shape

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

(10,)

array([[1., 1., 1.],
       [1., 1., 1.]])

(2, 3)

In [81]:
np.eye(5) # 5*5的单位矩阵

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
np.eye(5,k=1)# 偏移主对角线1个单位的伪单位矩阵

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [83]:
np.full((2,4),5)# 元组传入大小，10表示填充数值

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [84]:
np.full((2,4),[1,2,5,8])# 每行填入相同的列表

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

【c】随机矩阵：`np.random`

最常用的随机生成函数为`rand`, `randn`, `randint`, `choice`，它们分别表示0-1均匀分布的随机数组、标准正态的随机数组、随机整数组和随机列表抽样：

In [88]:
np.random.rand(5)# 生成服从0-1均匀分布的五个随机数

array([0.4975204 , 0.06536258, 0.5417184 , 0.57535069, 0.47127047])

In [89]:
np.random.rand(3,4) # 注意这里传入的不是元组，每个维度大小分开输入

array([[0.0395179 , 0.892471  , 0.08559529, 0.60955914],
       [0.23562462, 0.98526337, 0.59440888, 0.05482448],
       [0.45106942, 0.90846612, 0.01762892, 0.64981351]])

对于服从区间`a`到`b`上的均匀分布可以如下生成：

In [90]:
a,b=3,10
(b-a)*np.random.rand(5)+a

array([4.46949387, 9.38399618, 5.60549116, 8.36454189, 8.60167798])

一般的，可以选择已有的库函数：

In [92]:
np.random.uniform(3,10,5)

array([9.11942544, 7.28770959, 3.3896037 , 4.5378811 , 7.55651276])

In [95]:
np.random.randn(5)
np.random.randn(4,3)

array([-1.20479885, -0.19830293,  0.07851352,  0.80999628, -0.24561153])

array([[ 1.19006879, -0.26447666, -0.55911701],
       [ 0.3644442 , -0.62151784, -0.37019866],
       [-0.9643017 ,  1.12752538, -1.56210268],
       [ 1.29251924, -0.95359382, -0.0243893 ]])

对于服从方差为$\sigma^2$均值为$\mu$的一元正态分布可以如下生成：

In [106]:
mu,sigma=3,2.5
mu+np.random.randn(10)*sigma

array([ 3.86120821,  4.9505406 ,  4.6988951 ,  1.26547694,  3.63204501,
       -0.30731249,  1.8750444 ,  3.18411002,  0.94930593,  1.61150881])

同样的，也可选择从已有函数生成：

In [107]:
np.random.normal(3,2.5,10) #输入参数分别为 mu，sigma，size
np.random.normal(3,2.5,10).shape

array([ 1.01845411, -0.73300068, -1.34046865,  4.18799956,  7.30532199,
        9.20276942,  4.40455518,  7.20950864,  2.94492524,  2.83456574])

(10,)

`randint`可以指定生成随机整数的最小值最大值（不包含）和维度大小：

In [109]:
low,high,size=3,10,(2,3)
np.random.randint(low,high,size)

array([[7, 7, 6],
       [7, 4, 6]])

`choice`可以从给定的列表中，以一定概率和方式抽取结果，当不指定概率`p`时为均匀采样，默认抽取方式为有放回抽样(`replace=True`)：

In [123]:
my_list = ["b","a","t","d"]
np.random.choice(my_list,2,replace=True,p=[0.1,0.7,0.1,0.1])
np.random.choice(my_list,2,replace=False,p=[0.1,0.7,0.1,0.1])
np.random.choice(my_list,2,replace=True,p=[0.1,0.0,0.8,0.1])
np.random.choice(my_list, (3,3),replace=True,p=[0.1,0.0,0.8,0.1])

array(['t', 'a'], dtype='<U1')

array(['d', 'a'], dtype='<U1')

array(['t', 't'], dtype='<U1')

array([['t', 't', 't'],
       ['b', 'd', 't'],
       ['t', 'b', 't']], dtype='<U1')

当返回的元素个数与原列表相同时，不放回抽样等价于使用`permutation`函数，即打散原列表：

In [124]:
np.random.permutation(my_list)

array(['d', 'a', 'b', 't'], dtype='<U1')

最后，需要提到的是随机种子，它能够固定随机数的输出结果：

In [ ]:
np.random.seed(12)
np.ra